apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  defaults:
    backendType: secretsManager
  secrets:
  - backendType: secretsManager
    mappings:
    - key: jx-basic-auth-user
      name: username
      property: username
    - key: jx-basic-auth-user
      name: password
      property: password
    name: jx-basic-auth-user-password
  - backendType: secretsManager
    mappings:
    - key: jx-basic-auth-htpasswd
      name: auth
    name: jx-basic-auth-htpasswd
  - backendType: secretsManager
    mappings:
    - key: lighthouse-hmac
      name: hmac
    name: lighthouse-hmac-token
  - backendType: secretsManager
    mappings:
    - key: lighthouse-oauth
      name: oauth
    name: lighthouse-oauth-token
  - backendType: secretsManager
    mappings:
    - key: jx-pipeline-user
      name: username
      property: username
    - key: jx-pipeline-user
      name: password
      property: token
    name: jx-pipeline-git-github-github
  - backendType: secretsManager
    mappings:
    - key: jx-pipeline-user
      name: username
      property: username
    - key: jx-pipeline-user
      name: password
      property: token
    name: tekton-git
  - backendType: secretsManager
    mappings:
    - key: jx-pipeline-user
      name: username
      property: username
    - key: jx-pipeline-user
      name: password
      property: token
    name: knative-git-user-pass
  - backendType: secretsManager
    mappings:
    - key: jx-docker
      name: username
      property: username
    - key: jx-docker
      name: password
      property: password
    - key: jx-docker
      name: email
      property: email
    - key: jx-docker
      name: host
      property: host
    name: knative-docker-user-pass
  - backendType: secretsManager
    mappings:
    - key: jx-admin-user
      name: password
    name: nexus
  - backendType: secretsManager
    mappings:
    - name: BASIC_AUTH_USER
      key: nexus
      property: username
    - name: BASIC_AUTH_PASS
      key: nexus
      property: password
    name: jenkins-x-bucketrepo
  - backendType: secretsManager
    mappings:
    - key: jx-admin-user
      name: BASIC_AUTH_USER
      property: username
    - key: jx-admin-user
      name: BASIC_AUTH_PASS
      property: password
    name: jenkins-x-chartmuseum
  - backendType: secretsManager
    mappings:
    - key: jx-maven-settings
      name: settings.xml
      property: settingsXml
    - key: jx-maven-settings
      name: settings-security.xml
      property: securityXml
    name: jenkins-maven-settings
